/*
SQLyog Ultimate v8.32 
MySQL - 5.1.58-community : Database - scctbi_etl_tst
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`scctbi_etl_tst` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `scctbi_etl_tst`;

/*Table structure for table `log_job` */

DROP TABLE IF EXISTS `log_job`;

CREATE TABLE `log_job` (
  `ID_JOB` int(10) DEFAULT NULL,
  `CHANNEL_ID` varchar(255) DEFAULT NULL,
  `JOBNAME` varchar(255) DEFAULT NULL,
  `STATUS` varchar(15) DEFAULT NULL,
  `LINES_READ` bigint(19) DEFAULT NULL,
  `LINES_WRITTEN` bigint(19) DEFAULT NULL,
  `LINES_UPDATED` bigint(19) DEFAULT NULL,
  `LINES_INPUT` bigint(19) DEFAULT NULL,
  `LINES_OUTPUT` bigint(19) DEFAULT NULL,
  `LINES_REJECTED` bigint(19) DEFAULT NULL,
  `ERRORS` bigint(19) DEFAULT NULL,
  `STARTDATE` timestamp NULL DEFAULT NULL,
  `ENDDATE` timestamp NULL DEFAULT NULL,
  `LOGDATE` timestamp NULL DEFAULT NULL,
  `DEPDATE` timestamp NULL DEFAULT NULL,
  `REPLAYDATE` timestamp NULL DEFAULT NULL,
  `EXECUTING_SERVER` varchar(255) DEFAULT NULL,
  `EXECUTING_USER` varchar(255) DEFAULT NULL,
  `START_JOB_ENTRY` varchar(255) DEFAULT NULL,
  `CLIENT` varchar(255) DEFAULT NULL,
  `LOG_FIELD` text,
  KEY `IDX_LOG_JOB_1` (`ID_JOB`),
  KEY `IDX_LOG_JOB_2` (`ERRORS`,`STATUS`,`JOBNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `log_job_channel` */

DROP TABLE IF EXISTS `log_job_channel`;

CREATE TABLE `log_job_channel` (
  `ID_BATCH` int(10) DEFAULT NULL,
  `CHANNEL_ID` varchar(255) DEFAULT NULL,
  `LOG_DATE` timestamp NULL DEFAULT NULL,
  `LOGGING_OBJECT_TYPE` varchar(255) DEFAULT NULL,
  `OBJECT_NAME` varchar(255) DEFAULT NULL,
  `OBJECT_COPY` varchar(255) DEFAULT NULL,
  `REPOSITORY_DIRECTORY` varchar(255) DEFAULT NULL,
  `FILENAME` varchar(255) DEFAULT NULL,
  `OBJECT_ID` varchar(255) DEFAULT NULL,
  `OBJECT_REVISION` varchar(255) DEFAULT NULL,
  `PARENT_CHANNEL_ID` varchar(255) DEFAULT NULL,
  `ROOT_CHANNEL_ID` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `log_job_step` */

DROP TABLE IF EXISTS `log_job_step`;

CREATE TABLE `log_job_step` (
  `ID_BATCH` int(10) DEFAULT NULL,
  `CHANNEL_ID` varchar(255) DEFAULT NULL,
  `LOG_DATE` timestamp NULL DEFAULT NULL,
  `TRANSNAME` varchar(255) DEFAULT NULL,
  `STEPNAME` varchar(255) DEFAULT NULL,
  `LINES_READ` bigint(19) DEFAULT NULL,
  `LINES_WRITTEN` bigint(19) DEFAULT NULL,
  `LINES_UPDATED` bigint(19) DEFAULT NULL,
  `LINES_INPUT` bigint(19) DEFAULT NULL,
  `LINES_OUTPUT` bigint(19) DEFAULT NULL,
  `LINES_REJECTED` bigint(19) DEFAULT NULL,
  `ERRORS` bigint(19) DEFAULT NULL,
  `RESULT` bit(1) DEFAULT NULL,
  `NR_RESULT_ROWS` bigint(19) DEFAULT NULL,
  `NR_RESULT_FILES` bigint(19) DEFAULT NULL,
  `COPY_NR` int(10) DEFAULT NULL,
  `LOG_FIELD` text,
  KEY `IDX_LOG_JOB_STEP_1` (`ID_BATCH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `log_trans` */

DROP TABLE IF EXISTS `log_trans`;

CREATE TABLE `log_trans` (
  `ID_BATCH` int(10) DEFAULT NULL,
  `CHANNEL_ID` varchar(255) DEFAULT NULL,
  `TRANSNAME` varchar(255) DEFAULT NULL,
  `STATUS` varchar(15) DEFAULT NULL,
  `LINES_READ` bigint(19) DEFAULT NULL,
  `LINES_WRITTEN` bigint(19) DEFAULT NULL,
  `LINES_UPDATED` bigint(19) DEFAULT NULL,
  `LINES_INPUT` bigint(19) DEFAULT NULL,
  `LINES_OUTPUT` bigint(19) DEFAULT NULL,
  `LINES_REJECTED` bigint(19) DEFAULT NULL,
  `ERRORS` bigint(19) DEFAULT NULL,
  `STARTDATE` timestamp NULL DEFAULT NULL,
  `ENDDATE` timestamp NULL DEFAULT NULL,
  `LOGDATE` timestamp NULL DEFAULT NULL,
  `DEPDATE` timestamp NULL DEFAULT NULL,
  `REPLAYDATE` timestamp NULL DEFAULT NULL,
  `EXECUTING_SERVER` varchar(255) DEFAULT NULL,
  `EXECUTING_USER` varchar(255) DEFAULT NULL,
  `CLIENT` varchar(255) DEFAULT NULL,
  `LOG_FIELD` text,
  KEY `IDX_LOG_TRANS_1` (`ID_BATCH`),
  KEY `IDX_LOG_TRANS_2` (`ERRORS`,`STATUS`,`TRANSNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `log_trans_channel` */

DROP TABLE IF EXISTS `log_trans_channel`;

CREATE TABLE `log_trans_channel` (
  `ID_BATCH` int(10) DEFAULT NULL,
  `CHANNEL_ID` varchar(255) DEFAULT NULL,
  `LOG_DATE` timestamp NULL DEFAULT NULL,
  `LOGGING_OBJECT_TYPE` varchar(255) DEFAULT NULL,
  `OBJECT_NAME` varchar(255) DEFAULT NULL,
  `OBJECT_COPY` varchar(255) DEFAULT NULL,
  `REPOSITORY_DIRECTORY` varchar(255) DEFAULT NULL,
  `FILENAME` varchar(255) DEFAULT NULL,
  `OBJECT_ID` varchar(255) DEFAULT NULL,
  `OBJECT_REVISION` varchar(255) DEFAULT NULL,
  `PARENT_CHANNEL_ID` varchar(255) DEFAULT NULL,
  `ROOT_CHANNEL_ID` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `log_trans_step` */

DROP TABLE IF EXISTS `log_trans_step`;

CREATE TABLE `log_trans_step` (
  `ID_BATCH` int(10) DEFAULT NULL,
  `CHANNEL_ID` varchar(255) DEFAULT NULL,
  `LOG_DATE` timestamp NULL DEFAULT NULL,
  `TRANSNAME` varchar(255) DEFAULT NULL,
  `STEPNAME` varchar(255) DEFAULT NULL,
  `STEP_COPY` int(10) DEFAULT NULL,
  `LINES_READ` bigint(19) DEFAULT NULL,
  `LINES_WRITTEN` bigint(19) DEFAULT NULL,
  `LINES_UPDATED` bigint(19) DEFAULT NULL,
  `LINES_INPUT` bigint(19) DEFAULT NULL,
  `LINES_OUTPUT` bigint(19) DEFAULT NULL,
  `LINES_REJECTED` bigint(19) DEFAULT NULL,
  `ERRORS` bigint(19) DEFAULT NULL,
  `LOG_FIELD` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_cluster` */

DROP TABLE IF EXISTS `r_cluster`;

CREATE TABLE `r_cluster` (
  `ID_CLUSTER` bigint(19) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `BASE_PORT` varchar(255) DEFAULT NULL,
  `SOCKETS_BUFFER_SIZE` varchar(255) DEFAULT NULL,
  `SOCKETS_FLUSH_INTERVAL` varchar(255) DEFAULT NULL,
  `SOCKETS_COMPRESSED` bit(1) DEFAULT NULL,
  `DYNAMIC_CLUSTER` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_CLUSTER`),
  UNIQUE KEY `PK__R_CLUSTE__313CD32658546CC0` (`ID_CLUSTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_cluster_slave` */

DROP TABLE IF EXISTS `r_cluster_slave`;

CREATE TABLE `r_cluster_slave` (
  `ID_CLUSTER_SLAVE` bigint(19) NOT NULL,
  `ID_CLUSTER` int(10) DEFAULT NULL,
  `ID_SLAVE` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID_CLUSTER_SLAVE`),
  UNIQUE KEY `PK__R_CLUSTE__18B577846FE59E75` (`ID_CLUSTER_SLAVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_condition` */

DROP TABLE IF EXISTS `r_condition`;

CREATE TABLE `r_condition` (
  `ID_CONDITION` bigint(19) NOT NULL,
  `ID_CONDITION_PARENT` int(10) DEFAULT NULL,
  `NEGATED` bit(1) DEFAULT NULL,
  `OPERATOR` varchar(255) DEFAULT NULL,
  `LEFT_NAME` varchar(255) DEFAULT NULL,
  `CONDITION_FUNCTION` varchar(255) DEFAULT NULL,
  `RIGHT_NAME` varchar(255) DEFAULT NULL,
  `ID_VALUE_RIGHT` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID_CONDITION`),
  UNIQUE KEY `PK__R_CONDIT__E1C2C887A981373B` (`ID_CONDITION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_database` */

DROP TABLE IF EXISTS `r_database`;

CREATE TABLE `r_database` (
  `ID_DATABASE` bigint(19) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ID_DATABASE_TYPE` int(10) DEFAULT NULL,
  `ID_DATABASE_CONTYPE` int(10) DEFAULT NULL,
  `HOST_NAME` varchar(255) DEFAULT NULL,
  `DATABASE_NAME` text,
  `PORT` int(10) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `SERVERNAME` varchar(255) DEFAULT NULL,
  `DATA_TBS` varchar(255) DEFAULT NULL,
  `INDEX_TBS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_DATABASE`),
  UNIQUE KEY `PK__R_DATABA__528ADAE19A6DC855` (`ID_DATABASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_database_attribute` */

DROP TABLE IF EXISTS `r_database_attribute`;

CREATE TABLE `r_database_attribute` (
  `ID_DATABASE_ATTRIBUTE` bigint(19) NOT NULL,
  `ID_DATABASE` int(10) DEFAULT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `VALUE_STR` text,
  PRIMARY KEY (`ID_DATABASE_ATTRIBUTE`),
  UNIQUE KEY `PK__R_DATABA__7F116C1333CF6388` (`ID_DATABASE_ATTRIBUTE`),
  UNIQUE KEY `IDX_R_DATABASE_ATTRIBUTE_AK` (`ID_DATABASE`,`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_database_contype` */

DROP TABLE IF EXISTS `r_database_contype`;

CREATE TABLE `r_database_contype` (
  `ID_DATABASE_CONTYPE` bigint(19) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_DATABASE_CONTYPE`),
  UNIQUE KEY `PK__R_DATABA__48AE2FBCFC6D0879` (`ID_DATABASE_CONTYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_database_type` */

DROP TABLE IF EXISTS `r_database_type`;

CREATE TABLE `r_database_type` (
  `ID_DATABASE_TYPE` bigint(19) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_DATABASE_TYPE`),
  UNIQUE KEY `PK__R_DATABA__F341A9B011AFA8E2` (`ID_DATABASE_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_dependency` */

DROP TABLE IF EXISTS `r_dependency`;

CREATE TABLE `r_dependency` (
  `ID_DEPENDENCY` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_DATABASE` int(10) DEFAULT NULL,
  `TABLE_NAME` varchar(255) DEFAULT NULL,
  `FIELD_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_DEPENDENCY`),
  UNIQUE KEY `PK__R_DEPEND__6D8BB5E79F82C358` (`ID_DEPENDENCY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_directory` */

DROP TABLE IF EXISTS `r_directory`;

CREATE TABLE `r_directory` (
  `ID_DIRECTORY` bigint(19) NOT NULL,
  `ID_DIRECTORY_PARENT` int(10) DEFAULT NULL,
  `DIRECTORY_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_DIRECTORY`),
  UNIQUE KEY `PK__R_DIRECT__4F010684B24C65C3` (`ID_DIRECTORY`),
  UNIQUE KEY `IDX_R_DIRECTORY_AK` (`ID_DIRECTORY_PARENT`,`DIRECTORY_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_element` */

DROP TABLE IF EXISTS `r_element`;

CREATE TABLE `r_element` (
  `ID_ELEMENT` bigint(19) NOT NULL,
  `ID_ELEMENT_TYPE` int(10) DEFAULT NULL,
  `NAME` text,
  PRIMARY KEY (`ID_ELEMENT`),
  UNIQUE KEY `PK__R_ELEMEN__5E00E551F510C445` (`ID_ELEMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_element_attribute` */

DROP TABLE IF EXISTS `r_element_attribute`;

CREATE TABLE `r_element_attribute` (
  `ID_ELEMENT_ATTRIBUTE` bigint(19) NOT NULL,
  `ID_ELEMENT` int(10) DEFAULT NULL,
  `ID_ELEMENT_ATTRIBUTE_PARENT` int(10) DEFAULT NULL,
  `ATTR_KEY` varchar(255) DEFAULT NULL,
  `ATTR_VALUE` text,
  PRIMARY KEY (`ID_ELEMENT_ATTRIBUTE`),
  UNIQUE KEY `PK__R_ELEMEN__F9490AB04AE0E61B` (`ID_ELEMENT_ATTRIBUTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_element_type` */

DROP TABLE IF EXISTS `r_element_type`;

CREATE TABLE `r_element_type` (
  `ID_ELEMENT_TYPE` bigint(19) NOT NULL,
  `ID_NAMESPACE` int(10) DEFAULT NULL,
  `NAME` text,
  `DESCRIPTION` text,
  PRIMARY KEY (`ID_ELEMENT_TYPE`),
  UNIQUE KEY `PK__R_ELEMEN__9A4549E49CAF6EB4` (`ID_ELEMENT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_job` */

DROP TABLE IF EXISTS `r_job`;

CREATE TABLE `r_job` (
  `ID_JOB` bigint(19) NOT NULL,
  `ID_DIRECTORY` int(10) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` text,
  `EXTENDED_DESCRIPTION` text,
  `JOB_VERSION` varchar(255) DEFAULT NULL,
  `JOB_STATUS` int(10) DEFAULT NULL,
  `ID_DATABASE_LOG` int(10) DEFAULT NULL,
  `TABLE_NAME_LOG` varchar(255) DEFAULT NULL,
  `CREATED_USER` varchar(255) DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT NULL,
  `MODIFIED_USER` varchar(255) DEFAULT NULL,
  `MODIFIED_DATE` timestamp NULL DEFAULT NULL,
  `USE_BATCH_ID` bit(1) DEFAULT NULL,
  `PASS_BATCH_ID` bit(1) DEFAULT NULL,
  `USE_LOGFIELD` bit(1) DEFAULT NULL,
  `SHARED_FILE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_JOB`),
  UNIQUE KEY `PK__R_JOB__2E3A6A10C0BD8307` (`ID_JOB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_job_attribute` */

DROP TABLE IF EXISTS `r_job_attribute`;

CREATE TABLE `r_job_attribute` (
  `ID_JOB_ATTRIBUTE` bigint(19) NOT NULL,
  `ID_JOB` int(10) DEFAULT NULL,
  `NR` int(10) DEFAULT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `VALUE_NUM` bigint(19) DEFAULT NULL,
  `VALUE_STR` text,
  PRIMARY KEY (`ID_JOB_ATTRIBUTE`),
  UNIQUE KEY `PK__R_JOB_AT__28C7000707CD30CD` (`ID_JOB_ATTRIBUTE`),
  UNIQUE KEY `IDX_JOB_ATTRIBUTE_LOOKUP` (`ID_JOB`,`CODE`,`NR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_job_hop` */

DROP TABLE IF EXISTS `r_job_hop`;

CREATE TABLE `r_job_hop` (
  `ID_JOB_HOP` bigint(19) NOT NULL,
  `ID_JOB` int(10) DEFAULT NULL,
  `ID_JOBENTRY_COPY_FROM` int(10) DEFAULT NULL,
  `ID_JOBENTRY_COPY_TO` int(10) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `EVALUATION` bit(1) DEFAULT NULL,
  `UNCONDITIONAL` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_JOB_HOP`),
  UNIQUE KEY `PK__R_JOB_HO__7E58E3270327F294` (`ID_JOB_HOP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_job_lock` */

DROP TABLE IF EXISTS `r_job_lock`;

CREATE TABLE `r_job_lock` (
  `ID_JOB_LOCK` bigint(19) NOT NULL,
  `ID_JOB` int(10) DEFAULT NULL,
  `ID_USER` int(10) DEFAULT NULL,
  `LOCK_MESSAGE` text,
  `LOCK_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID_JOB_LOCK`),
  UNIQUE KEY `PK__R_JOB_LO__B1E1AB16B51A008B` (`ID_JOB_LOCK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_job_note` */

DROP TABLE IF EXISTS `r_job_note`;

CREATE TABLE `r_job_note` (
  `ID_JOB` int(10) DEFAULT NULL,
  `ID_NOTE` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_jobentry` */

DROP TABLE IF EXISTS `r_jobentry`;

CREATE TABLE `r_jobentry` (
  `ID_JOBENTRY` bigint(19) NOT NULL,
  `ID_JOB` int(10) DEFAULT NULL,
  `ID_JOBENTRY_TYPE` int(10) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` text,
  PRIMARY KEY (`ID_JOBENTRY`),
  UNIQUE KEY `PK__R_JOBENT__FC5F5707D789951A` (`ID_JOBENTRY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_jobentry_attribute` */

DROP TABLE IF EXISTS `r_jobentry_attribute`;

CREATE TABLE `r_jobentry_attribute` (
  `ID_JOBENTRY_ATTRIBUTE` bigint(19) NOT NULL,
  `ID_JOB` int(10) DEFAULT NULL,
  `ID_JOBENTRY` int(10) DEFAULT NULL,
  `NR` int(10) DEFAULT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `VALUE_NUM` decimal(13,2) DEFAULT NULL,
  `VALUE_STR` text,
  PRIMARY KEY (`ID_JOBENTRY_ATTRIBUTE`),
  UNIQUE KEY `PK__R_JOBENT__9011DCAA0A338892` (`ID_JOBENTRY_ATTRIBUTE`),
  UNIQUE KEY `IDX_R_JOBENTRY_ATTRIBUTE_LOOKUP` (`ID_JOBENTRY_ATTRIBUTE`,`CODE`,`NR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_jobentry_copy` */

DROP TABLE IF EXISTS `r_jobentry_copy`;

CREATE TABLE `r_jobentry_copy` (
  `ID_JOBENTRY_COPY` bigint(19) NOT NULL,
  `ID_JOBENTRY` int(10) DEFAULT NULL,
  `ID_JOB` int(10) DEFAULT NULL,
  `ID_JOBENTRY_TYPE` int(10) DEFAULT NULL,
  `NR` int(10) DEFAULT NULL,
  `GUI_LOCATION_X` int(10) DEFAULT NULL,
  `GUI_LOCATION_Y` int(10) DEFAULT NULL,
  `GUI_DRAW` bit(1) DEFAULT NULL,
  `PARALLEL` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_JOBENTRY_COPY`),
  UNIQUE KEY `PK__R_JOBENT__552CDA3B524D0A57` (`ID_JOBENTRY_COPY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_jobentry_database` */

DROP TABLE IF EXISTS `r_jobentry_database`;

CREATE TABLE `r_jobentry_database` (
  `ID_JOB` int(10) DEFAULT NULL,
  `ID_JOBENTRY` int(10) DEFAULT NULL,
  `ID_DATABASE` int(10) DEFAULT NULL,
  KEY `IDX_R_JOBENTRY_DATABASE_LU1` (`ID_JOB`),
  KEY `IDX_R_JOBENTRY_DATABASE_LU2` (`ID_DATABASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_jobentry_type` */

DROP TABLE IF EXISTS `r_jobentry_type`;

CREATE TABLE `r_jobentry_type` (
  `ID_JOBENTRY_TYPE` bigint(19) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_JOBENTRY_TYPE`),
  UNIQUE KEY `PK__R_JOBENT__672BFD21927DEE5D` (`ID_JOBENTRY_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_log` */

DROP TABLE IF EXISTS `r_log`;

CREATE TABLE `r_log` (
  `ID_LOG` bigint(19) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ID_LOGLEVEL` int(10) DEFAULT NULL,
  `LOGTYPE` varchar(255) DEFAULT NULL,
  `FILENAME` varchar(255) DEFAULT NULL,
  `FILEEXTENTION` varchar(255) DEFAULT NULL,
  `ADD_DATE` bit(1) DEFAULT NULL,
  `ADD_TIME` bit(1) DEFAULT NULL,
  `ID_DATABASE_LOG` int(10) DEFAULT NULL,
  `TABLE_NAME_LOG` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_LOG`),
  UNIQUE KEY `PK__R_LOG__2DBE379DDACE9805` (`ID_LOG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_loglevel` */

DROP TABLE IF EXISTS `r_loglevel`;

CREATE TABLE `r_loglevel` (
  `ID_LOGLEVEL` bigint(19) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_LOGLEVEL`),
  UNIQUE KEY `PK__R_LOGLEV__A4E51A4B88FCC5F9` (`ID_LOGLEVEL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_namespace` */

DROP TABLE IF EXISTS `r_namespace`;

CREATE TABLE `r_namespace` (
  `ID_NAMESPACE` bigint(19) NOT NULL,
  `NAME` varchar(7999) DEFAULT NULL,
  PRIMARY KEY (`ID_NAMESPACE`),
  UNIQUE KEY `PK__R_NAMESP__C43C194002D7AC1C` (`ID_NAMESPACE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_note` */

DROP TABLE IF EXISTS `r_note`;

CREATE TABLE `r_note` (
  `ID_NOTE` bigint(19) NOT NULL,
  `VALUE_STR` text,
  `GUI_LOCATION_X` int(10) DEFAULT NULL,
  `GUI_LOCATION_Y` int(10) DEFAULT NULL,
  `GUI_LOCATION_WIDTH` int(10) DEFAULT NULL,
  `GUI_LOCATION_HEIGHT` int(10) DEFAULT NULL,
  `FONT_NAME` text,
  `FONT_SIZE` int(10) DEFAULT NULL,
  `FONT_BOLD` bit(1) DEFAULT NULL,
  `FONT_ITALIC` bit(1) DEFAULT NULL,
  `FONT_COLOR_RED` int(10) DEFAULT NULL,
  `FONT_COLOR_GREEN` int(10) DEFAULT NULL,
  `FONT_COLOR_BLUE` int(10) DEFAULT NULL,
  `FONT_BACK_GROUND_COLOR_RED` int(10) DEFAULT NULL,
  `FONT_BACK_GROUND_COLOR_GREEN` int(10) DEFAULT NULL,
  `FONT_BACK_GROUND_COLOR_BLUE` int(10) DEFAULT NULL,
  `FONT_BORDER_COLOR_RED` int(10) DEFAULT NULL,
  `FONT_BORDER_COLOR_GREEN` int(10) DEFAULT NULL,
  `FONT_BORDER_COLOR_BLUE` int(10) DEFAULT NULL,
  `DRAW_SHADOW` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_NOTE`),
  UNIQUE KEY `PK__R_NOTE__AB084D78527F2C07` (`ID_NOTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_partition` */

DROP TABLE IF EXISTS `r_partition`;

CREATE TABLE `r_partition` (
  `ID_PARTITION` bigint(19) NOT NULL,
  `ID_PARTITION_SCHEMA` int(10) DEFAULT NULL,
  `PARTITION_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_PARTITION`),
  UNIQUE KEY `PK__R_PARTIT__0663AF0C1D6DA95C` (`ID_PARTITION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_partition_schema` */

DROP TABLE IF EXISTS `r_partition_schema`;

CREATE TABLE `r_partition_schema` (
  `ID_PARTITION_SCHEMA` bigint(19) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DYNAMIC_DEFINITION` bit(1) DEFAULT NULL,
  `PARTITIONS_PER_SLAVE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_PARTITION_SCHEMA`),
  UNIQUE KEY `PK__R_PARTIT__5D9A6B729AB7560C` (`ID_PARTITION_SCHEMA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_repository_log` */

DROP TABLE IF EXISTS `r_repository_log`;

CREATE TABLE `r_repository_log` (
  `ID_REPOSITORY_LOG` bigint(19) NOT NULL,
  `REP_VERSION` varchar(255) DEFAULT NULL,
  `LOG_DATE` timestamp NULL DEFAULT NULL,
  `LOG_USER` varchar(255) DEFAULT NULL,
  `OPERATION_DESC` text,
  PRIMARY KEY (`ID_REPOSITORY_LOG`),
  UNIQUE KEY `PK__R_REPOSI__915C0631D4CB29AB` (`ID_REPOSITORY_LOG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_slave` */

DROP TABLE IF EXISTS `r_slave`;

CREATE TABLE `r_slave` (
  `ID_SLAVE` bigint(19) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `HOST_NAME` varchar(255) DEFAULT NULL,
  `PORT` varchar(255) DEFAULT NULL,
  `WEB_APP_NAME` varchar(255) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `PROXY_HOST_NAME` varchar(255) DEFAULT NULL,
  `PROXY_PORT` varchar(255) DEFAULT NULL,
  `NON_PROXY_HOSTS` varchar(255) DEFAULT NULL,
  `MASTER` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_SLAVE`),
  UNIQUE KEY `PK__R_SLAVE__007A8CFB17DE0CBB` (`ID_SLAVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_step` */

DROP TABLE IF EXISTS `r_step`;

CREATE TABLE `r_step` (
  `ID_STEP` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` text,
  `ID_STEP_TYPE` int(10) DEFAULT NULL,
  `DISTRIBUTE` bit(1) DEFAULT NULL,
  `COPIES` int(10) DEFAULT NULL,
  `GUI_LOCATION_X` int(10) DEFAULT NULL,
  `GUI_LOCATION_Y` int(10) DEFAULT NULL,
  `GUI_DRAW` bit(1) DEFAULT NULL,
  `COPIES_STRING` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_STEP`),
  UNIQUE KEY `PK__R_STEP__F2B3856F9DF4F062` (`ID_STEP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_step_attribute` */

DROP TABLE IF EXISTS `r_step_attribute`;

CREATE TABLE `r_step_attribute` (
  `ID_STEP_ATTRIBUTE` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_STEP` int(10) DEFAULT NULL,
  `NR` int(10) DEFAULT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `VALUE_NUM` bigint(19) DEFAULT NULL,
  `VALUE_STR` text,
  PRIMARY KEY (`ID_STEP_ATTRIBUTE`),
  UNIQUE KEY `PK__R_STEP_A__FEE368C52EE7E36E` (`ID_STEP_ATTRIBUTE`),
  UNIQUE KEY `IDX_R_STEP_ATTRIBUTE_LOOKUP` (`ID_STEP`,`CODE`,`NR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_step_database` */

DROP TABLE IF EXISTS `r_step_database`;

CREATE TABLE `r_step_database` (
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_STEP` int(10) DEFAULT NULL,
  `ID_DATABASE` int(10) DEFAULT NULL,
  KEY `IDX_R_STEP_DATABASE_LU1` (`ID_TRANSFORMATION`),
  KEY `IDX_R_STEP_DATABASE_LU2` (`ID_DATABASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_step_type` */

DROP TABLE IF EXISTS `r_step_type`;

CREATE TABLE `r_step_type` (
  `ID_STEP_TYPE` bigint(19) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `HELPTEXT` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_STEP_TYPE`),
  UNIQUE KEY `PK__R_STEP_T__B78AD949F2B5E970` (`ID_STEP_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_attribute` */

DROP TABLE IF EXISTS `r_trans_attribute`;

CREATE TABLE `r_trans_attribute` (
  `ID_TRANS_ATTRIBUTE` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `NR` int(10) DEFAULT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `VALUE_NUM` bigint(19) DEFAULT NULL,
  `VALUE_STR` text,
  PRIMARY KEY (`ID_TRANS_ATTRIBUTE`),
  UNIQUE KEY `PK__R_TRANS___A87E0A95BC4E1A13` (`ID_TRANS_ATTRIBUTE`),
  UNIQUE KEY `IDX_TRANS_ATTRIBUTE_LOOKUP` (`ID_TRANSFORMATION`,`CODE`,`NR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_cluster` */

DROP TABLE IF EXISTS `r_trans_cluster`;

CREATE TABLE `r_trans_cluster` (
  `ID_TRANS_CLUSTER` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_CLUSTER` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID_TRANS_CLUSTER`),
  UNIQUE KEY `PK__R_TRANS___0F0DEC3BE5FFA182` (`ID_TRANS_CLUSTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_hop` */

DROP TABLE IF EXISTS `r_trans_hop`;

CREATE TABLE `r_trans_hop` (
  `ID_TRANS_HOP` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_STEP_FROM` int(10) DEFAULT NULL,
  `ID_STEP_TO` int(10) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_TRANS_HOP`),
  UNIQUE KEY `PK__R_TRANS___0D45C7F5ECCF4CF3` (`ID_TRANS_HOP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_lock` */

DROP TABLE IF EXISTS `r_trans_lock`;

CREATE TABLE `r_trans_lock` (
  `ID_TRANS_LOCK` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_USER` int(10) DEFAULT NULL,
  `LOCK_MESSAGE` text,
  `LOCK_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TRANS_LOCK`),
  UNIQUE KEY `PK__R_TRANS___F0448113D05B8007` (`ID_TRANS_LOCK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_note` */

DROP TABLE IF EXISTS `r_trans_note`;

CREATE TABLE `r_trans_note` (
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_NOTE` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_partition_schema` */

DROP TABLE IF EXISTS `r_trans_partition_schema`;

CREATE TABLE `r_trans_partition_schema` (
  `ID_TRANS_PARTITION_SCHEMA` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_PARTITION_SCHEMA` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID_TRANS_PARTITION_SCHEMA`),
  UNIQUE KEY `PK__R_TRANS___930CDED304E86C2B` (`ID_TRANS_PARTITION_SCHEMA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_slave` */

DROP TABLE IF EXISTS `r_trans_slave`;

CREATE TABLE `r_trans_slave` (
  `ID_TRANS_SLAVE` bigint(19) NOT NULL,
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_SLAVE` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID_TRANS_SLAVE`),
  UNIQUE KEY `PK__R_TRANS___3CB22C5A1103CCB1` (`ID_TRANS_SLAVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_trans_step_condition` */

DROP TABLE IF EXISTS `r_trans_step_condition`;

CREATE TABLE `r_trans_step_condition` (
  `ID_TRANSFORMATION` int(10) DEFAULT NULL,
  `ID_STEP` int(10) DEFAULT NULL,
  `ID_CONDITION` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_transformation` */

DROP TABLE IF EXISTS `r_transformation`;

CREATE TABLE `r_transformation` (
  `ID_TRANSFORMATION` bigint(19) NOT NULL,
  `ID_DIRECTORY` int(10) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` text,
  `EXTENDED_DESCRIPTION` text,
  `TRANS_VERSION` varchar(255) DEFAULT NULL,
  `TRANS_STATUS` int(10) DEFAULT NULL,
  `ID_STEP_READ` int(10) DEFAULT NULL,
  `ID_STEP_WRITE` int(10) DEFAULT NULL,
  `ID_STEP_INPUT` int(10) DEFAULT NULL,
  `ID_STEP_OUTPUT` int(10) DEFAULT NULL,
  `ID_STEP_UPDATE` int(10) DEFAULT NULL,
  `ID_DATABASE_LOG` int(10) DEFAULT NULL,
  `TABLE_NAME_LOG` varchar(255) DEFAULT NULL,
  `USE_BATCHID` bit(1) DEFAULT NULL,
  `USE_LOGFIELD` bit(1) DEFAULT NULL,
  `ID_DATABASE_MAXDATE` int(10) DEFAULT NULL,
  `TABLE_NAME_MAXDATE` varchar(255) DEFAULT NULL,
  `FIELD_NAME_MAXDATE` varchar(255) DEFAULT NULL,
  `OFFSET_MAXDATE` decimal(12,2) DEFAULT NULL,
  `DIFF_MAXDATE` decimal(12,2) DEFAULT NULL,
  `CREATED_USER` varchar(255) DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT NULL,
  `MODIFIED_USER` varchar(255) DEFAULT NULL,
  `MODIFIED_DATE` timestamp NULL DEFAULT NULL,
  `SIZE_ROWSET` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID_TRANSFORMATION`),
  UNIQUE KEY `PK__R_TRANSF__EFEBD7335D5EB6D0` (`ID_TRANSFORMATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_user` */

DROP TABLE IF EXISTS `r_user`;

CREATE TABLE `r_user` (
  `ID_USER` bigint(19) NOT NULL,
  `LOGIN` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_USER`),
  UNIQUE KEY `PK__R_USER__95F48440079B6249` (`ID_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_value` */

DROP TABLE IF EXISTS `r_value`;

CREATE TABLE `r_value` (
  `ID_VALUE` bigint(19) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `VALUE_TYPE` varchar(255) DEFAULT NULL,
  `VALUE_STR` varchar(255) DEFAULT NULL,
  `IS_NULL` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_VALUE`),
  UNIQUE KEY `PK__R_VALUE__D68F67601496D99F` (`ID_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `r_version` */

DROP TABLE IF EXISTS `r_version`;

CREATE TABLE `r_version` (
  `ID_VERSION` bigint(19) NOT NULL,
  `MAJOR_VERSION` int(10) DEFAULT NULL,
  `MINOR_VERSION` int(10) DEFAULT NULL,
  `UPGRADE_DATE` timestamp NULL DEFAULT NULL,
  `IS_UPGRADE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID_VERSION`),
  UNIQUE KEY `PK__R_VERSIO__4441D1C7918FDFDB` (`ID_VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
